<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msg="http://bced.wallonie.be/services/inscription/messages/v1" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns2="http://www.w3.org/2006/05/addressing/wsdl" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/jms/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://bced.wallonie.be/services/inscription/v1" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:err="http://bced.wallonie.be/data/common/error/v1" xmlns:sobo="http://bced.wallonie.be/common/sentOnBehalfOf/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://bced.wallonie.be/services/inscription/v1">
  <types>
    <xs:schema xmlns:ns1="http://bced.wallonie.be/services/inscription/messages/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://bced.wallonie.be/services/inscription/v1">
      <xs:import namespace="http://bced.wallonie.be/services/inscription/messages/v1" schemaLocation="xsd/BCEDInscriptionMessages_v1.xsd"></xs:import>
      <xs:import namespace="http://bced.wallonie.be/data/common/error/v1" schemaLocation="xsd/error_v1.xsd"></xs:import>
      <xs:import namespace="http://bced.wallonie.be/common/sentOnBehalfOf/v1" schemaLocation="xsd/sentOnBehalfOf_v1.xsd"></xs:import>
    </xs:schema>
  </types>
  <message name="closeInscriptionResponse">
    <part name="parameters" element="msg:closeInscriptionResponse">
    </part>
  </message>
  <message name="extendInscription">
    <part name="parameters" element="msg:extendInscription">
    </part>
  </message>
  <message name="cancelInscriptionResponse">
    <part name="parameters" element="msg:cancelInscriptionResponse">
    </part>
  </message>
  <message name="extendInscriptionResponse">
    <part name="parameters" element="msg:extendInscriptionResponse">
    </part>
  </message>
  <message name="closeInscription">
    <part name="parameters" element="msg:closeInscription">
    </part>
  </message>
  <message name="searchInscriptions">
    <part name="parameters" element="msg:searchInscriptions">
    </part>
  </message>
  <message name="fault">
    <part name="parameters" element="err:error">
    </part>
  </message>
  <message name="publishInscription">
    <part name="parameters" element="msg:publishInscription">
    </part>
  </message>
  <message name="searchInscriptionsResponse">
    <part name="parameters" element="msg:searchInscriptionsResponse">
    </part>
  </message>
  <message name="cancelInscription">
    <part name="parameters" element="msg:cancelInscription">
    </part>
  </message>
  <message name="SentOnBehalfOf">
    <part name="SentOnBehalfOf" element="sobo:sentOnBehalfOf">
    </part>
  </message>
  <message name="publishInscriptionResponse">
    <part name="parameters" element="msg:publishInscriptionResponse">
    </part>
  </message>
  <portType name="inscriptionV1PortType">
    <operation name="publishInscription">
      <input message="tns:publishInscription">
    </input>
      <output message="tns:publishInscriptionResponse">
    </output>
      <fault name="fault" message="tns:fault">
    </fault>
    </operation>
    <operation name="cancelInscription">
      <input message="tns:cancelInscription">
    </input>
      <output message="tns:cancelInscriptionResponse">
    </output>
      <fault name="fault" message="tns:fault">
    </fault>
    </operation>
    <operation name="searchInscriptions">
      <input message="tns:searchInscriptions">
    </input>
      <output message="tns:searchInscriptionsResponse">
    </output>
      <fault name="fault" message="tns:fault">
    </fault>
    </operation>
    <operation name="extendInscription">
      <input message="tns:extendInscription">
    </input>
      <output message="tns:extendInscriptionResponse">
    </output>
      <fault name="fault" message="tns:fault">
    </fault>
    </operation>
    <operation name="closeInscription">
      <input message="tns:closeInscription">
    </input>
      <output message="tns:closeInscriptionResponse">
    </output>
      <fault name="fault" message="tns:fault">
    </fault>
    </operation>
  </portType>
  <binding name="inscriptionV1SoapBinding" type="tns:inscriptionV1PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#inscriptionV1PortType_inscriptionV1SoapBinding_policy"></wsp:PolicyReference>
    <operation name="publishInscription">
      <soap:operation soapAction="http://bced.wallonie.be/services/inscription/v1/publishInscription"></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#publishInscription_input_policy"></wsp:PolicyReference>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#publishInscription_output_policy"></wsp:PolicyReference>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"></soap:fault>
      </fault>
    </operation>
    <operation name="cancelInscription">
      <soap:operation soapAction="http://bced.wallonie.be/services/inscription/v1/cancelInscription"></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#cancelInscription_input_policy"></wsp:PolicyReference>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#cancelInscription_output_policy"></wsp:PolicyReference>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"></soap:fault>
      </fault>
    </operation>
    <operation name="searchInscriptions">
      <soap:operation soapAction="http://bced.wallonie.be/services/inscription/v1/searchInscriptions"></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#searchInscriptions_input_policy"></wsp:PolicyReference>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#searchInscriptions_output_policy"></wsp:PolicyReference>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"></soap:fault>
      </fault>
    </operation>
    <operation name="extendInscription">
      <soap:operation soapAction="http://bced.wallonie.be/services/inscription/v1/extendInscription"></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#extendInscription_input_policy"></wsp:PolicyReference>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#extendInscription_output_policy"></wsp:PolicyReference>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"></soap:fault>
      </fault>
    </operation>
    <operation name="closeInscription">
      <soap:operation soapAction="http://bced.wallonie.be/services/inscription/v1/closeInscription"></soap:operation>
      <input>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#closeInscription_input_policy"></wsp:PolicyReference>
      </input>
      <output>
        <soap:body use="literal"></soap:body>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#closeInscription_output_policy"></wsp:PolicyReference>
      </output>
      <fault name="fault">
        <soap:fault name="fault" use="literal"></soap:fault>
      </fault>
    </operation>
  </binding>
  <service name="inscriptionsV1">
    <port name="inscriptionV1Port" binding="tns:inscriptionV1SoapBinding">
      <soap:address location="https://services-web.tq.etnic.be:11443/bced/inscription/v1"></soap:address>
    </port>
  </service>
    <wsp:UsingPolicy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsdl:Required="true"></wsp:UsingPolicy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="closeInscription_input_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="closeInscription_output_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="extendInscription_input_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="extendInscription_output_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="searchInscriptions_input_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="searchInscriptions_output_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="cancelInscription_input_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="cancelInscription_output_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="publishInscription_input_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="publishInscription_output_policy">
    <sp:SignedParts xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <sp:Body></sp:Body>
    </sp:SignedParts>
  </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="inscriptionV1PortType_inscriptionV1SoapBinding_policy">
    <wsp:All>
      <wsp:Policy>
        <sp:AsymmetricBinding xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <wsp:Policy>
            <sp:InitiatorToken>
              <wsp:Policy>
                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:WssX509V3Token10></sp:WssX509V3Token10>
                  </wsp:Policy>
                </sp:X509Token>
              </wsp:Policy>
            </sp:InitiatorToken>
            <sp:RecipientToken>
              <wsp:Policy>
                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                  <wsp:Policy>
                    <sp:WssX509V3Token10></sp:WssX509V3Token10>
                  </wsp:Policy>
                </sp:X509Token>
              </wsp:Policy>
            </sp:RecipientToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256></sp:Basic256>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict></sp:Strict>
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp></sp:IncludeTimestamp>
            <sp:OnlySignEntireHeadersAndBody></sp:OnlySignEntireHeadersAndBody>
          </wsp:Policy>
        </sp:AsymmetricBinding>
        <sp:Wss10 xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <wsp:Policy>
            <sp:MustSupportRefKeyIdentifier></sp:MustSupportRefKeyIdentifier>
            <sp:MustSupportRefIssuerSerial></sp:MustSupportRefIssuerSerial>
          </wsp:Policy>
        </sp:Wss10>
        <sp:SupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <wsp:Policy>
            <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssX509V3Token10></sp:WssX509V3Token10>
                <sp:RequireKeyIdentifierReference></sp:RequireKeyIdentifierReference>
              </wsp:Policy>
            </sp:X509Token>
          </wsp:Policy>
        </sp:SupportingTokens>
      </wsp:Policy>
    </wsp:All>
  </wsp:Policy>
</definitions>
