# -*- encoding: utf-8 -*-
##############################################################################
#
#    Copyright (c) 2015 be-cloud.be
#                       Jerome Sonnet <jerome.sonnet@be-cloud.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
import logging

from openerp import api, fields, models, tools, _
from openerp.exceptions import MissingError

_logger = logging.getLogger(__name__)

from openerp.addons.report_xlsx.report.report_xlsx import ReportXlsx

class SaturnXlsx(ReportXlsx):

    def generate_xlsx_report(self, workbook, data, saturn):
        saturn.ensure_one()
        sheet = workbook.add_worksheet('main')
        
        date_format = workbook.add_format({'num_format': 'dd/mm/yyyy'})
        
        i = 0
        sheet.write(i, 0, 'Code Fase de l’Ecole supérieure des Arts')
        sheet.write(i, 1, 'Année académique en cours (= année N)')
        sheet.write(i, 2, 'Type d''études')
        sheet.write(i, 3, 'Domaine d''études')
        sheet.write(i, 4, 'Cycle d''études et durée du cycle')
        sheet.write(i, 5, 'Section d''études (Musique) ou AESS (tous les domaines)')
        sheet.write(i, 6, 'Option')
        sheet.write(i, 7, 'Année d''études dans le cycle')
        sheet.write(i, 8, 'Inscriptions multiples')
        sheet.write(i, 9, 'Jeunes Talents (Musique)')
        sheet.write(i, 10, 'Finalité du 2e cycle')
        sheet.write(i, 11, 'Spécialité (Musique)')
        sheet.write(i, 12, 'Nom de l''étudiant')
        sheet.write(i, 13, 'Premier prénom de l''étudiant')
        sheet.write(i, 14, 'Initiales des autres prénoms')
        sheet.write(i, 15, 'Numéro matricule')
        sheet.write(i, 16, 'Sexe')
        sheet.write(i, 17, 'Nationalité')
        sheet.write(i, 18, 'Lieu de naissance')
        sheet.write(i, 19, 'Pays du lieu de naissance')
        sheet.write(i, 20, 'Date de naissance de l''étudiant')
        sheet.write(i, 21, 'Domicile légal en Belgique')
        sheet.write(i, 22, 'Domicile légal à l''étranger')
        sheet.write(i, 23, 'Numéro de Registre national')
        sheet.write(i, 24, 'Régulier / Libre')
        sheet.write(i, 25, 'Date d’abandon')
        sheet.write(i, 26, 'Ancien/Nouveau')
        sheet.write(i, 27, 'Etalement')
        sheet.write(i, 28, 'Mobilité')
        sheet.write(i, 29, 'Première génération')
        sheet.write(i, 30, 'Type de mobilité')
        sheet.write(i, 31, 'Nationalité de l’étudiant au regard du financement')
        sheet.write(i, 32, 'Modalité de l''inscription au regard du financement')
        sheet.write(i, 33, 'Etudiant boursier')
        sheet.write(i, 34, 'Minerval')
        sheet.write(i, 35, 'Date de réception du paiement du minerval')
        sheet.write(i, 36, 'Droit d’inscription spécifique (DIS)')
        sheet.write(i, 37, 'Date de réception du paiement du droit d’inscription spécifique')
        sheet.write(i, 38, 'Etudiant de condition modeste')
        sheet.write(i, 39, 'Titre d’accès à la première année du cycle court ou du premier cycle du type long')
        sheet.write(i, 40, 'Année de délivrance du titre d’accès à la 1re année d’études')
        sheet.write(i, 41, 'Type de secondaire obligatoire suivi')
        sheet.write(i, 42, 'Etablissement d’enseignement de la FWB ou de la DG où le titre d’accès a été obtenu')
        sheet.write(i, 43, 'Pays dans lequel le titre d’accès équivalent a été obtenu')
        sheet.write(i, 44, 'Titre d’accès aux autres années que la première année des études de type court ou long')
        sheet.write(i, 45, 'Diplôme obtenu dans l’enseignement supérieur')
        sheet.write(i, 46, 'Année d’obtention du diplôme en F2')
        sheet.write(i, 47, 'Autre diplôme obtenu dans l’enseignement supérieur (1)')
        sheet.write(i, 48, 'Année d’obtention du diplôme en F4')
        sheet.write(i, 49, 'Pays dans lequel le diplôme indiqué à la variable F2 a été obtenu')
        sheet.write(i, 50, 'Activité principale au cours de l’année académique n‐1')
        sheet.write(i, 51, 'Etablissement d’enseignement de la FWB concerné par G2')
        sheet.write(i, 52, 'Domaine d’études concerné par G2')
        sheet.write(i, 53, 'Année d’études se rapportant à G2')
        sheet.write(i, 54, 'Résultats se rapportant à G2')
        sheet.write(i, 55, 'Activité principale au cours de l’année académique n‐2')
        sheet.write(i, 56, 'Etablissement d’enseignement de la FWB concerné par G7')
        sheet.write(i, 57, 'Domaine d’études concerné par G7')
        sheet.write(i, 58, 'Année d’études se rapportant G7')
        sheet.write(i, 59, 'Résultats se rapportant à G7')
        sheet.write(i, 60, 'Activité principale au cours de l’année académique n‐3')
        sheet.write(i, 61, 'Etablissement d’enseignement de la FWB concerné par G12')
        sheet.write(i, 62, 'Domaine d’études concerné par G12')
        sheet.write(i, 63, 'Année d’études se rapportant à G12')
        sheet.write(i, 64, 'Résultats se rapportant à G12')
        sheet.write(i, 65, 'Activité principale au cours de l’année académique n‐4')
        sheet.write(i, 66, 'Etablissement d’enseignement de la FWB concerné par G17')
        sheet.write(i, 67, 'Domaine d’études concerné par G17')
        sheet.write(i, 68, 'Année d’études se rapportant à G17')
        sheet.write(i, 69, 'Résultats se rapportant à G17')
        sheet.write(i, 70, 'Activité principale au cours de l’année académique n‐5')
        sheet.write(i, 71, 'Etablissement d’enseignement de la FWB concerné par G22')
        sheet.write(i, 72, 'Domaine d’études concerné par G22')
        sheet.write(i, 73, 'Année d’études se rapportant à G22')
        sheet.write(i, 74, 'Résultats se rapportant à G22')
        sheet.write(i, 75, 'Pays de l’activité académique se rapportant à G2')
        sheet.write(i, 76, 'Résultats de la 1re session (juillet 2013)')
        sheet.write(i, 77, 'Résultats de la 2e session (septembre 2013)')
        sheet.write(i, 78, 'Résultats de session prolongée')
        sheet.write(i, 79, 'Date du diplôme')   
        i = 1
        for bloc_id in saturn.bloc_ids:
            sheet.write(i, 0, bloc_id.field_a1)
            sheet.write(i, 1, bloc_id.field_a2.name)
            sheet.write(i, 2, bloc_id.field_a3)
            sheet.write(i, 3, bloc_id.field_a4.saturn_code)
            sheet.write(i, 4, bloc_id.field_a5.saturn_code)
            sheet.write(i, 5, bloc_id.field_a6.saturn_code)
            sheet.write(i, 6, bloc_id.field_a7.saturn_code)
            sheet.write(i, 7, bloc_id.field_a8)
            sheet.write(i, 8, bloc_id.field_a9)
            sheet.write(i, 9, bloc_id.field_a10)
            sheet.write(i, 10, bloc_id.field_a11)
            sheet.write(i, 11, bloc_id.field_a12.saturn_code)
            sheet.write(i, 12, bloc_id.field_b1)
            sheet.write(i, 13, bloc_id.field_b2)
            sheet.write(i, 14, bloc_id.field_b3)
            sheet.write(i, 15, bloc_id.field_b4)
            sheet.write(i, 16, bloc_id.field_b5)
            sheet.write(i, 17, bloc_id.field_b6.name)
            sheet.write(i, 18, bloc_id.field_b7)
            sheet.write(i, 19, bloc_id.field_b8.name)
            sheet.write_datetime(i, 20, fields.Date.from_string(bloc_id.field_b9), date_format)
            sheet.write(i, 21, bloc_id.field_b10)
            sheet.write(i, 22, bloc_id.field_b11)
            sheet.write(i, 23, bloc_id.field_b12)
            sheet.write(i, 24, bloc_id.field_c1)
            sheet.write(i, 25, bloc_id.field_c2)
            sheet.write(i, 26, bloc_id.field_c3)
            sheet.write(i, 27, bloc_id.field_c4)
            sheet.write(i, 28, bloc_id.field_c5)
            sheet.write(i, 29, bloc_id.field_c14)
            sheet.write(i, 30, bloc_id.field_c19)
            sheet.write(i, 31, bloc_id.field_d1)
            sheet.write(i, 32, bloc_id.field_d2)
            sheet.write(i, 33, bloc_id.field_d3)
            sheet.write(i, 34, bloc_id.field_d4)
            sheet.write(i, 35, bloc_id.field_d5)
            sheet.write(i, 36, bloc_id.field_d6)
            sheet.write(i, 37, bloc_id.field_d7)
            sheet.write(i, 38, bloc_id.field_d8)
            sheet.write(i, 39, bloc_id.field_e1)
            sheet.write(i, 40, bloc_id.field_e2.name)
            sheet.write(i, 41, bloc_id.field_e3)
            sheet.write(i, 42, bloc_id.field_e4.code_fase)
            sheet.write(i, 43, bloc_id.field_e5.name)
            sheet.write(i, 44, bloc_id.field_f1)
            sheet.write(i, 45, bloc_id.field_f2)
            sheet.write(i, 46, bloc_id.field_f3.name)
            sheet.write(i, 47, bloc_id.field_f4)
            sheet.write(i, 48, bloc_id.field_f5.name)
            sheet.write(i, 49, bloc_id.field_f10.name)
            sheet.write(i, 50, bloc_id.field_g2)
            sheet.write(i, 51, bloc_id.field_g3.code_fase)
            sheet.write(i, 52, bloc_id.field_g4.code)
            sheet.write(i, 53, bloc_id.field_g5)
            sheet.write(i, 54, bloc_id.field_g6)
            sheet.write(i, 55, bloc_id.field_g7)
            sheet.write(i, 56, bloc_id.field_g8.code_fase)
            sheet.write(i, 57, bloc_id.field_g9.code)
            sheet.write(i, 58, bloc_id.field_g10)
            sheet.write(i, 59, bloc_id.field_g11)
            sheet.write(i, 60, bloc_id.field_g12)
            sheet.write(i, 61, bloc_id.field_g13.code_fase)
            sheet.write(i, 62, bloc_id.field_g14.code)
            sheet.write(i, 63, bloc_id.field_g15)
            sheet.write(i, 64, bloc_id.field_g16)
            sheet.write(i, 65, bloc_id.field_g17)
            sheet.write(i, 66, bloc_id.field_g18.code_fase)
            sheet.write(i, 67, bloc_id.field_g19.code)
            sheet.write(i, 68, bloc_id.field_g20)
            sheet.write(i, 69, bloc_id.field_g21)
            sheet.write(i, 70, bloc_id.field_g22)
            sheet.write(i, 71, bloc_id.field_g23.code_fase)
            sheet.write(i, 72, bloc_id.field_g24.code)
            sheet.write(i, 73, bloc_id.field_g25)
            sheet.write(i, 74, bloc_id.field_g26)
            sheet.write(i, 75, bloc_id.field_g27.name)
            sheet.write(i, 76, bloc_id.field_h1)
            sheet.write(i, 77, bloc_id.field_h2)
            sheet.write(i, 78, bloc_id.field_h3)
            _logger.info(bloc_id.field_h4)
            sheet.write_datetime(i, 79, fields.Date.from_string(bloc_id.field_h4), date_format)
            i = i + 1

SaturnXlsx('report.school.saturn.xlsx','school.saturn')